### ISSUE TITLE
laravel5.4.9 setFetchMode()

### ISSUE THREAD

**Issue by woisk** [ignasbernotas/laravel-model-generator#33]
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Database\MySqlConnection::setFetchMode()

**Comment by woisk** [comment]
why?

**Comment by iberflow** [comment]
Laravel 5.4 API must've changed. I currently don't have much time on my hands so a PR is welcome:)

**Comment by acousticksan** [comment]
I fix this, please approve PR

**Comment by jhonkrave** [comment]
I have same problem :/

**Comment by iberflow** [comment]
I have commented on your PR. The code you've submitted (regarding the fetch mode) has no effect. You're creating a new Dispatcher instance which means that your listener will never be fired. You need to take the Dispatcher from the service container. I am currently unable to spend time on this, so please fix your PR and I'll merge it.

**Comment by trinvh** [comment]
+1

**Comment by iberflow** [comment]
Fixed with 006fbe9 and released in 1.1.5

**Comment by jacobsantos** [comment]
I am still seeing this problem on Laravel 5.3. Are older versions of Laravel unsupported?

EDIT: Sorry, my problem is unrelated.

**Comment by iberflow** [comment]
@jacobsantos all good then? :)

**Comment by jacobsantos** [comment]
@ignasbernotas Yes, I made PR #37 to track my issue.
